# TP1

## Repositorios de información

## Ejercicio 1

- Descomprimir el archivo clima.tgz de la carpeta data
- Convertir cada archivo a Dataframe y mostrarlo en pantalla

In [ ]:
import tarfile
from os import listdir

folder_name = "carpeta"

objetoTar = tarfile.open("data/clima.tgz", "r")
# Extraer todo el contenido en la carpeta
base_directory = f"data/{folder_name}/
objetoTar.extractall(base_directory)
# Cerrar lectura
objetoTar.close()
file_names = listdir(base_directory)
for name in file_names:
    df = pd.read_csv(f"{base_directory}{name}")
    display(df)

## Ejercicio 2

- Obtener de la API de <a href="https://wikimedia.org/api/rest_v1/#/Pageviews%20data">Wikimedia </a> la cantidad de visitas en este año a la página Albert Einstein por día.
- Mostrar el Dataframe obtenido por pantalla

In [ ]:
import requests
import pandas as pd
url = "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/es.wikipedia.org/all-access/all-agents/Albert_Einstein/daily/20210101/20211230"
respuesta = requests.get(url, headers={'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/91.0'})
data = respuesta.json()                       
df = pd.DataFrame(data["items"])
df

## Ejercicio 3

- Crear una base de datos MySQL
- Crear una tabla que contenga nombre, apellido y teléfono
- Obtener de la base de datos la lista de personas ordenada por apellido de forma descendente
- Mostrar el Dataframe resultante por pantalla

## Ejercicio 4

- Obtener de la API <a href="https://date.nager.at/swagger/index.html">Nager.Date</a> las fiestas nacionales argentinas para el 2021
- Mostrar el dataframe resultante por pantalla

In [ ]:
import requests
import pandas as pd
url = "https://date.nager.at/api/v3/PublicHolidays/2021/AR"
respuesta = requests.get(url, headers={'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/91.0'})
data = respuesta.json()                       
df = pd.DataFrame(data)
df

## Ejercicio 5

- Obtener una tabla informativa de una página a elección con Web Scrapping
- Mostrar el Dataframe resultante por pantalla

In [3]:
import requests
import pandas as pd
url = "https://www.promiedos.com.ar/primera"
tables = pd.read_html(url, header=0, index_col=0)
tables[0]

               Equipo  Pts  PJ  PG  PE  PP  GF  GC  DIF
#
1               Lanus   19   9   6   1   2  19  15    4
2       Independiente   18   9   5   3   1  10   4    6
3    Estudiantes (LP)   16   8   5   1   2  15   7    8
4         Racing Club   16   9   4   4   1   8   1    7
5        Talleres (C)   16   8   5   1   2  12   7    5
6         River Plate   14   8   4   2   2  15   6    9
7               Colon   14   9   4   2   3   8  13   -5
8            Aldosivi   13   9   4   1   4  11  12   -1
9      Def y Justicia   12   9   3   3   3  11   9    2
10          Patronato   12   8   3   3   2   8   6    2
11         Argentinos   12   8   3   3   2   7   5    2
12       Boca Juniors   11   9   2   5   2   6   6    0
13            Newells   11   8   3   2   3   9  10   -1
14        Atl Tucuman   11   8   3   2   3   9  11   -2
15              Velez   10   9   2   4   3   9   6    3
16    Rosario Central   10   9   3   1   5  13  11    2
17      Gimnasia (LP)   10   9   2   4   3   7   9   -2
18      Sarmiento (J)   10   8   3   1   4   8  11   -3
19         Godoy Cruz   10   9   3   1   5  10  15   -5
20              Union    9   8   2   3   3   9  10   -1
21            Huracan    9   9   1   6   2   6   7   -1
22           Platense    9   9   2   3   4  12  14   -2
23           Banfield    8   9   1   5   3   7  11   -4
24        San Lorenzo    8   8   2   2   4   5  11   -6
25  Central Cba (SdE)    7   9   1   4   4   9  13   -4
26            Arsenal    6   9   1   3   5   5  18  -13